# Copy this file, rename it to `local.yml`, and enter your credentials to run the bot.
arisa:
  credentials:
    username: <JIRA user name>
    password: <plain text password>
    dandelionToken: <Dandelion token>
  debug:
    # You can add some debug options here, see `ArisaConfig.kt`
