# This workflow will build a Java project with Gradle and deploy it

name: Build and push

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean installDist
    - name: Upload new libraries
      uses: urielsalis/rsync-deploy@v1.1
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_PORT: 22
        FOLDER: "build/install/arisa-kt/lib"
        ARGS: "-avh --delete"
        SERVER_IP: ${{ secrets.REMOTE_HOST }}
        USERNAME: ${{ secrets.REMOTE_USER }}
        SERVER_DESTINATION: /home/ubuntu/arisa-kt
    - name: Upload new binaries
      uses: urielsalis/rsync-deploy@v1.1
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_PORT: 22
        FOLDER: "build/install/arisa-kt/bin"
        ARGS: "-avh --delete"
        SERVER_IP: ${{ secrets.REMOTE_HOST }}
        USERNAME: ${{ secrets.REMOTE_USER }}
        SERVER_DESTINATION: /home/ubuntu/arisa-kt
    - name: Run internal deploy script
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        user: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        command: |
          /usr/bin/screen -ls | /bin/grep Detached | /usr/bin/cut -d. -f1 | /usr/bin/awk '{print $1}' | /usr/bin/xargs /bin/kill
          sleep 1
          /usr/bin/screen -d -m bash -c '/home/ubuntu/arisa-kt/bin/arisa-kt; exec sh'
          
        args: "-tt"
