# This workflow will build a Java project with Gradle and deploy it

name: Build and push

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradlewrapper-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradlewrapper-
    - name: Build with Gradle
      run: ./gradlew clean installDist
    - name: Upload new libraries
      uses: urielsalis/rsync-deploy@v1.1
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_PORT: 22
        FOLDER: "build/install/arisa-kt/lib"
        ARGS: "-avh --delete"
        SERVER_IP: ${{ secrets.REMOTE_HOST }}
        USERNAME: arisakt
        SERVER_DESTINATION: /home/arisakt/arisa-kt
    - name: Upload new binaries
      uses: urielsalis/rsync-deploy@v1.1
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_PORT: 22
        FOLDER: "build/install/arisa-kt/bin"
        ARGS: "-avh --delete"
        SERVER_IP: ${{ secrets.REMOTE_HOST }}
        USERNAME: arisakt
        SERVER_DESTINATION: /home/arisakt/arisa-kt
    - name: Upload new configuration
      uses: urielsalis/rsync-deploy@v1.2
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_PORT: 22
        FOLDER: "arisa.json"
        ARGS: "-avh --delete"
        SERVER_IP: ${{ secrets.REMOTE_HOST }}
        USERNAME: arisakt
        SERVER_DESTINATION: /home/arisakt/arisa-kt
    - name: Run internal deploy script
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        user: arisakt
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        command: |
          /usr/bin/screen -ls | /bin/egrep 'Detached|Attached' | /usr/bin/cut -d. -f1 | /usr/bin/awk '{print $1}' | /usr/bin/xargs /bin/kill
          sleep 1
          cd arisa-kt
          /usr/bin/screen -d -m bash -c '/home/arisakt/arisa-kt/bin/arisa-kt; exec sh'

        args: "-tt"
